module.exports={
    APP_ID:'wx43c3b5e1b112b5b0',
    APP_SECRET:'12323ffbc36e112c5ea847fc76bb5d54',
    ENV_PROD:'production',
    ENV_DEV:'development',
    ACCESS_TOKEN:'ACCESS_TOKEN',
    ACHIEVE:{
        SIGN_EASY:'1',
        SIGN_EASY_LABEL:'签到新人',
        SIGN_NORMAL:'2',
        SIGN_NORMAL_LABEL:'签到达人',
        SIGN_HARD:'3',
        SIGN_HARD_LABEL:'签到狂人',
        SIGN_GOD:'4',
        SIGN_GOD_LABEL:'签到狂魔',
    },
    toast:{
        RISKY_HINT:'检测到违规内容，请修改后重试',
    }
}
